### PR TITLE
Navigation bar to use chakra and new design

### PR DESCRIPTION
**Pull request by jishanarora**
Change the design of the navbar and utilize chakra-ui. #67 

The Navbar should be responsive for all breakpoints

image
image
image
image
image

Closes https://github.com/devin-efendy/fujiji/issues/67

### CODE REVIEW

**Review by wynonagcc — APPROVED** [review]

**Review by wynonagcc — COMMENTED** [review]
Oh, instead of a `Search` button, can we have a search bar?

**Comment by devin-efendy** [comment]
lgtm! 

Storybook for NavBar is not working, though. We can push this issue into next sprint.

**Review by devin-efendy — APPROVED** [review]

**Comment by devin-efendy** [comment]
Also, can you please write "Closes #67" in the description? So it will automatically closes that issue

**Comment by jishanarora** [comment]
> Oh, instead of a `Search` button, can we have a search bar?

Its just I have added the search bar in the landing page and search page. This is just a shortcut to go to search page

**Pull request merged**
