### PR TITLE
feat/#51: Build a Form to create a listing

### LINKED ISSUE #51: [TASK] Build a Form to create an ad listing
### Description

Implement a form for seller to post an ad listing. Make this re-usable as we can probably use this for updating the listing as well.

### Acceptance Criteria:

- Seller should be able to fill this form and upload an image of the product
- Form should contains: `title`, `description`, `date`, `condition`, `location`, `image`
- Use a state hook and container pattern to maintain the component states

### Link

**User Story**: #6

### PR DESCRIPTION
**Pull request by devin-efendy**
# Description

Created a Form that able to `CREATE`, `UPDATE`, and `DELETE` listing.

This form can be re-used for editing the listing as a seller.

There will be an alert dialog if user want to _Delete_ a listing or _Discard_ their changes

`isUpdate` prop is used to determine if we want to render a `CREATE` or `UPDATE` form

`onSubmit` prop is a callback that we can pass functions for `POST` or `UPDATE` request. The same applies for `onDelete`

Fixed Jest error where it does not properly map uncovered lines.

Closes #51 

# Demo

Screen Shot 2022-02-23 at 2 53 30 PM

Screen Shot 2022-02-23 at 2 53 22 PM

Screen Shot 2022-02-22 at 9 16 33 PM

https://user-images.githubusercontent.com/36686154/155255729-3c30a0a4-2ad1-4098-9f18-09469751e121.mov

### CODE REVIEW

**Review by wynonagcc — COMMENTED** [review]
The seller should be able to add price and category of the listing (i.e., table, chair, etc.) here too, right? Or am I missing something?

**Review by jishanarora — CHANGES_REQUESTED** [review]
We need to show contact details on the listing as well, just in case the user doesn't enter the details in the description. We can add a toggle to ask the customer to show their contact details along with the option of adding alternate number/email.

**Comment by devin-efendy** [comment]
Yep, I completely forgot about the price, category, and contact details 😅. Thanks!

Will be adding them soon. Also, do we need to update the SIgn Up to ask for user's contact details then?

**Comment by jishanarora** [comment]
> Yep, I completely forgot about the price, category, and contact details 😅. Thanks!
> 
> Will be adding them soon. Also, do we need to update the SIgn Up to ask for user's contact details then?

No, just the name, username/email and password but contact details should be there in profile before posting any ad.

**Comment by devin-efendy** [comment]
Alright sounds good. Just to confirm we don't want to put their actual contact details in the actual listing, right? It's like we are exposing their personal info lol. 

Unless they actually put them in the description I guess.

**Comment by devin-efendy** [comment]
Discussed offline. We are not implementing alternate contact details. We will use the email of seller account as default contact details

**Review by wynonagcc — APPROVED** [review]

**Comment by devin-efendy** [comment]
@jishanarora are we good to merge this in?

**Pull request merged**
